// practice-vue-last/src/components/SearchResult.vue
<template>
  <ul v-if="searchResult.length" class="list">
    <li v-for="item in searchResult">
      <img v-bind:src="item.image" v-bind:alt="item.image">
      <p>{{item.name}}</p>
    </li>
  </ul>
  <p v-else>검색 결과가 없습니다</p>
</template>

<script>
export default {
  props: ['searchResult'],
  data () {
    return {

    }
  },  
  methods: {
    
  }
}
</script>

// practice-react/src/components/SearchResult.jsx
import React, { useEffect, useState } from 'react';
import SearchModel from '../models/SearchModel';

const SearchResult = props => {
  const { query } = props;

  const [data, setData] = useState([]);

  useEffect(() => {        
    if (query) {            
      SearchModel.list(query).then(data => {                
        setData(data);        
      });
    }        
  }, [query]);

  console.log('SearchResult render()');
  return (
    <div id="search-result">
      {
        data.length > 0 ?
        <ul>
          {
            data.map((item, index) => {
              return (
                <li key={item.id}>
                  <img src={item.image} alt={item.image} />
                  <p>{item.name}</p>
                </li>
              )
            })
          }
        </ul>
        :
        '검색 결과가 없습니다'
      }      
    </div>
  );
}

export default SearchResult;
