// practice-react/src/components/SearchForm.jsx
import React, { useState, useEffect } from 'react';

const SearchForm = props => {
  const { onSearch, onReset } = props;

  const [value, setValue] = useState('');

  useEffect(() => {
    if (value.length === 0) {
      onReset();
    }
  });

  const onChange = (e) => {
    setValue(e.target.value);
  }

  const onSubmit = (e) => {
    e.preventDefault();
    onSearch(value);
  }

  const onClick = (e) => {
    setValue('');
  }

  return (
    <form onSubmit={onSubmit}>
      <input type="text" placeholder="검색어를 입력하세요" autoFocus value={value} onChange={onChange} />
      {(value.length > 0) && <button type="reset" className="btn-reset" onClick={onClick}></button>}
    </form>
  );
}

export default SearchForm;

// practice-vue-last/src/components/SearchForm.vue
<template>
  <form v-on:submit.prevent="onSubmit" v-on:reset="onReset">
    <input type="text" v-model="value" placeholder="검색어를 입력하세요" v-on:keyup="onKeyup" autofocus>
    <button v-show="value.length" type="reset" class="btn-reset"></button>
  </form>
</template>

<script>
export default {
  props: ['query'],
  data () {
    return {
      value: '',      
    }
  },
  watch: {
    query(newVal, oldVal) {
      this.value = this.query;
    }
  },
  methods: {
    onKeyup(e) {      
      this.$emit('@onKeyup', this.value);
      if(this.value.length === 0) this.onReset();
    },
    onReset(e) {      
      this.$emit('@onReset');
    },
    onSubmit(e) {      
      this.$emit('@onSubmit');
    }
  }
}
</script>
