// practice-react-redux-thunk/src/components/SearchForm.jsx
import React, { useState, useEffect } from 'react';

const SearchForm = props => {
  const {query, search, reset} = props;
  const [value, setValue] = useState('');

  useEffect(()=>{
    setValue(query);
  }, [query]);

  const onChange = e => {
    setValue(e.target.value);
    if (!e.target.value.length) {
      reset();
    }
  }

  const onSubmit = e => {
    e.preventDefault();
    search(value);
  }

  const onReset = e => {
    e.preventDefault();
    reset();
  }
  
  return (
    <form onSubmit={onSubmit} onReset={onReset}>
      <input type="text" placeholder="검색어를 입력하세요" autoFocus value={value} onChange={onChange} />
      {value.length > 0 && <button type="reset" className="btn-reset"></button>}
    </form>
  );
}

export default SearchForm;

// practice-vue-last/src/components/SearchForm.vue
<template>
  <form v-on:submit.prevent="onSubmit" v-on:reset="onReset">
    <input type="text" v-model="value" placeholder="검색어를 입력하세요" v-on:keyup="onKeyup" autofocus>
    <button v-show="value.length" type="reset" class="btn-reset"></button>
  </form>
</template>

<script>
export default {
  props: ['query'],
  data () {
    return {
      value: '',      
    }
  },
  watch: {
    query(newVal, oldVal) {
      this.value = this.query;
    }
  },
  methods: {
    onKeyup(e) {      
      this.$emit('@onKeyup', this.value);
      if(this.value.length === 0) this.onReset();
    },
    onReset(e) {      
      this.$emit('@onReset');
    },
    onSubmit(e) {      
      this.$emit('@onSubmit');
    }
  }
}
</script>
