// practice-react-last/src/components/SearchForm.jsx
import React from 'react'
import { useEffect, useState } from 'react';

const SearchForm = props => {
    const [keyword, setKeyword] = useState('');
    const [showRemoveBtn, setShowRemoveBtn] = useState(false);

    useEffect(() => {
        setKeyword(props.query);
        setShowRemoveBtn(props.query.length > 0)
    }, [props.query]);

    const handleChange = e => {
        setKeyword(e.target.value);
        setShowRemoveBtn(e.target.value.length > 0);
        if (e.target.value.length === 0) handleReset();
    }

    const handleSubmit = e => {
        e.preventDefault();
        props.onSubmit(keyword);
    }

    const handleReset = e => {
        if (e) e.preventDefault();
        setKeyword('');
        setShowRemoveBtn(false);
        props.onReset();
    }

    return (
        <form onSubmit={handleSubmit} onReset={handleReset}>
            <input type="text" placeholder="검색어를 입력하세요" value={keyword} onChange={handleChange} autoFocus />
            {showRemoveBtn && <button type="reset" className="btn-reset"></button>}
        </form>
    )
}

export default SearchForm

// practice-vue-last/src/components/SearchForm.vue
<template>
  <form v-on:submit.prevent="onSubmit" v-on:reset="onReset">
    <input type="text" v-model="value" placeholder="검색어를 입력하세요" v-on:keyup="onKeyup" autofocus>
    <button v-show="value.length" type="reset" class="btn-reset"></button>
  </form>
</template>

<script>
export default {
  props: ['query'],
  data () {
    return {
      value: '',      
    }
  },
  watch: {
    query(newVal, oldVal) {
      this.value = this.query;
    }
  },
  methods: {
    onKeyup(e) {      
      this.$emit('@onKeyup', this.value);
      if(this.value.length === 0) this.onReset();
    },
    onReset(e) {      
      this.$emit('@onReset');
    },
    onSubmit(e) {      
      this.$emit('@onSubmit');
    }
  }
}
</script>
