// practice-vue-last/src/components/SearchResult.vue
<template>
  <ul v-if="searchResult.length" class="list">
    <li v-for="item in searchResult">
      <img v-bind:src="item.image" v-bind:alt="item.image">
      <p>{{item.name}}</p>
    </li>
  </ul>
  <p v-else>검색 결과가 없습니다</p>
</template>

<script>
export default {
  props: ['searchResult'],
  data () {
    return {

    }
  },  
  methods: {
    
  }
}
</script>

// practice-react-last/src/components/SearchResult.jsx
import React from 'react'

const SearchResult = props => {
    if (props.loading) {
        return (
            <div>loading...</div>
        )
    }
    else if (props.result.length > 0) {
        return (
            <div>
                <ul className="list">
                    {props.result.map(item =>
                        <li key={item.id}>
                            <img src={item.image} alt={item.image} />
                            <p>{item.name}</p>
                        </li>
                    )}
                </ul>
            </div>
        )
    }
    else {
        return (
            <div>검색 결과가 없습니다</div>
        )
    }

}

export default SearchResult
