// 4-single-file-component/src/App.vue
<template>
  <div>
    <header>
      <h2 class="container">검색</h2>
    </header>
    <div class="container">
      <search-form v-bind:value="query" v-on:@submit="onSubmit" v-on:@reset="onReset"></search-form>
      <div class="content">
        <div v-if="submitted">
          <search-result v-bind:data="searchResult" v-bind:query="query"></search-result>
        </div>
        <div v-else>
          <tabs v-bind:tabs="tabs" v-bind:selected-tab="selectedTab" v-on:@change="onClickTab"></tabs>
          <div v-if="selectedTab === tabs[0]">
            <list v-bind:data="keywords" type="keywords" v-on:@click="onClickKeyword"></list>
          </div>
          <div v-else>
            <list v-bind:data="history" type="history" v-on:@click="onClickKeyword" v-on:@remove="onClickRemoveHistory">
            </list>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import SearchModel from './models/SearchModel.js'
import KeywordModel from './models/KeywordModel.js'
import HistoryModel from './models/HistoryModel.js'

import FormComponent from './components/FormComponent.vue'
import ResultComponent from './components/ResultComponent.vue'
import ListComponent from './components/ListComponent.vue'
import TabComponent from './components/TabComponent.vue'

export default {
  name: 'app',
  data () {
    return {
      query: '',
      submitted: false,
      tabs: ['추천 검색어', '최근 검색어'],
      selectedTab: '',
      keywords: [],
      history: [],
      searchResult: []
    }
  },
  components: {
    'search-form': FormComponent,
    'search-result': ResultComponent,
    'list': ListComponent,
    'tabs': TabComponent
  },
  created() {
    this.selectedTab = this.tabs[0]
    this.fetchKeyword()
    this.fetchHistory()
  },
  methods: {
    onSubmit(query) {
      this.query = query
      this.search()
    },    
    onReset(e) {
      this.resetForm()
    },
    onClickTab(tab) {
      this.selectedTab = tab
    },
    onClickKeyword(keyword) {
      this.query = keyword;
      this.search()
    },
    onClickRemoveHistory(keyword) {
      HistoryModel.remove(keyword)
      this.fetchHistory()
    },
    fetchKeyword() {
      KeywordModel.list().then(data => {
        this.keywords = data
      })
    },
    fetchHistory() {
      HistoryModel.list().then(data => {
        this.history = data
      })
    },
    search() {
      SearchModel.list().then(data => {
        this.submitted = true
        this.searchResult = data
      })
      HistoryModel.add(this.query)
      this.fetchHistory()
    },
    resetForm() {
      this.query = ''
      this.submitted = false
      this.searchResult = []
    }
  }
}
</script>

// practice-react/src/App.js
import React, { useEffect, useState, useCallback } from 'react';
import Header from './components/Header';
import SearchForm from './components/SearchForm';
import Tab from './components/Tab';
import SearchKeyword from './components/SearchKeyword';
import SearchHistory from './components/SearchHistory';
import SearchResult from './components/SearchResult';

import SearchModel from './models/SearchModel';
import KeywordModel from './models/KeywordModel';
import HistoryModel from './models/HistoryModel';

import { TAB_NAME } from './constants';

function App() {
  const [query, setQuery] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [searchResult, setSearchResult] = useState([]);
  const [selectedTab, setSelectedTab] = useState(TAB_NAME[0]);
  const [keywords, setKeywords] = useState([]);
  const [history, setHistory] = useState([]);

  const fetchKeyword = () => {
    KeywordModel.list().then(data => {
      setKeywords(data);
    })
  }

  const fetchHistory = () => {
    HistoryModel.list().then(data => {
      setHistory(data);
    })
  }

  const addHistory = useCallback(keyword => {
    HistoryModel.add(keyword);
    fetchHistory();
  }, [])

  const removeHistory = useCallback(keyword => {
    HistoryModel.remove(keyword);
    fetchHistory();
  }, [])

  const onSearch = useCallback(query => {
    setSubmitted(true);
    setQuery(query);
    if (query) {
      SearchModel.list(query).then(data => {
        setSearchResult(data);
      });
    }
    addHistory(query);
  }, [addHistory])

  const onReset = useCallback(() => {
    setSubmitted(false);
    setQuery('');
  }, [])

  const onClickTab = useCallback(tabName => {
    setSelectedTab(tabName);
  }, [])



  const onRemoveHistory = useCallback(keyword => {
    removeHistory(keyword);
  }, [removeHistory])

  useEffect(() => {
    if (query.length === 0) {
      onReset();
    }
  }, [query.length, onReset]);

  useEffect(() => {
    if (selectedTab === TAB_NAME[0]) {
      fetchKeyword();
    }
    else {
      fetchHistory();
    }

  }, [selectedTab])

  console.log('App render()');
  return (
    <>
      <Header />
      <div className="container">
        <SearchForm query={query} setQuery={setQuery} onSearch={onSearch} onReset={onReset} />
        <div className="content">
          {
            submitted === false ?
              <>
                <Tab selectedTab={selectedTab} onClickTab={onClickTab} />
                {
                  selectedTab === TAB_NAME[0] ?
                    <SearchKeyword keywords={keywords} onSearch={onSearch} />
                    :
                    <SearchHistory history={history} onSearch={onSearch} onRemoveHistory={onRemoveHistory} />
                }
              </>
              :
              <SearchResult searchResult={searchResult} submitted={submitted} />
          }
        </div>
      </div>
    </>
  );
}

export default App;
