// practice-react-redux-thunk/src/components/SearchList.jsx
import React from 'react';

const SearchList = props => {
  const { type, list, submitted, loading, search, onClickHistoryRemove } = props;
  const onClickList = keyword => {
    search(keyword);
  }
  const onClickRemove = (e, keyword) => {
    e.stopPropagation();
    onClickHistoryRemove(keyword);
  }

  return (
    <div>
      {!submitted && (
        !loading ? (
          list.length ? (
            <ul className="list">
              {list.map((item, index) => (
                <li key={item.keyword} onClick={(e)=>onClickList(item.keyword)}>
                  {type === 'keyword' && <span className="number">{index + 1}</span>}
                  {item.keyword}
                  {type === 'history' && <span className="date">{item.date}</span>}
                  {type === 'history' && <button className="btn-remove" onClick={(e)=>onClickRemove(e, item.keyword)}></button>}
                </li>
              ))}
            </ul>
          ) : (<p>추천 검색어가 없습니다</p>)
        ) : (<div>Loading...</div>)
      )}
    </div>
  );
}

export default SearchList;

// practice-vue-total/src/components/SearchList.vue
<template>
  <div v-if="searchList.length">
    <ul class="list">
    <li v-for="(item, index) in searchList" v-on:click="onClickList(item.keyword)">
      <span v-if="keywordType" class="number">{{index+1}}</span>
      {{item.keyword}}
      <span v-if="historyType" class="date">{{item.date}}</span>
      <button v-if="historyType" class="btn-reset" v-on:click.stop="onClickHistoryRemove(item.keyword)"></button>
    </li>
  </ul>
  </div>
  <div v-else>
    <p v-if="keywordType">추천 검색어가 없습니다</p>
    <p v-if="historyType">최근 검색어가 없습니다</p>
  </div>
</template>

<script>
export default {
  props: ['type','searchList'],
  computed: {
    keywordType() {
      return this.type === 'keyword' ;
    },
    historyType() {
      return this.type === 'history';
    }
  },
  methods: {
    onClickList(keyword) {
      this.$emit('@onClickList', keyword);
    },
    onClickHistoryRemove(keyword) {
      this.$emit('@onClickHistoryRemove', keyword)
    }
  }
}
</script>
