// practice-react-redux-thunk/src/components/SearchForm.jsx
import React, { useState, useEffect } from 'react';

const SearchForm = props => {
  const {query, search, reset} = props;
  const [value, setValue] = useState('');

  useEffect(()=>{
    setValue(query);
  }, [query]);

  const onChange = e => {
    setValue(e.target.value);
    if (!e.target.value.length) {
      reset();
    }
  }

  const onSubmit = e => {
    e.preventDefault();
    search(value);
  }

  const onReset = e => {
    e.preventDefault();
    reset();
  }
  
  return (
    <form onSubmit={onSubmit} onReset={onReset}>
      <input type="text" placeholder="검색어를 입력하세요" autoFocus value={value} onChange={onChange} />
      {value.length > 0 && <button type="reset" className="btn-reset"></button>}
    </form>
  );
}

export default SearchForm;

// practice-vue-total/src/components/SearchForm.vue
<template>
  <form v-on:submit.prevent="onSubmit" v-on:reset.prevent="onReset">
    <input type="text" placeholder="검색어를 입력하세요" autofocus v-model="value" v-on:keyup="onKeyup">
    <button type="reset" class="btn-reset" v-show="value.length"></button>
  </form>
</template>

<script>
export default {
  props: ['query'],
  data() {
    return {
      value: ''
    }
  },
  watch: {
    query(newQuery, oldQuery){
      this.value = newQuery;
    }
  },
  methods: {
    onSubmit() {      
      this.$emit('@submit', this.value);
    },
    onKeyup() {
      if(!this.value.length) {
        this.onReset();
      }      
    },
    onReset() {
      this.$emit('@reset');
    }
  }
}
</script>

<style>

</style>
