// practice-react-redux-thunk/src/components/Tab.jsx
import React from 'react';
import { tabs } from '../constants';


const Tab = props => {
  const { selectedTab, changeTab, submitted } = props;
  const onClick = tab => {
    changeTab(tab);
  }

  if(!submitted){
    return (    
      <ul id="tabs" className="tabs">
        {
          tabs.map(tab => <li key={tab} className={tab === selectedTab ? 'active' : null} onClick={()=>onClick(tab)}>{tab}</li>)
        }
      </ul>
    );
  }
  else{
    return null;
  }
}

export default Tab;

// practice-vue-total/src/components/Tab.vue
<template>
  <ul id="tabs" class="tabs">
    <li v-for="tab in tabs" v-bind:class="{active: tab===selectedTab}" v-on:click="onClick(tab)">{{tab}}</li>    
  </ul>
</template>

<script>
export default {
  props: ['tabs', 'selectedTab'],
  methods: {
    onClick(tab) {
      this.$emit('@click', tab);
    }
  }
}
</script>
