// practice-react-last/src/components/Tab.jsx
import React from 'react'

import { tabs } from '../constants/index'

const Tab = props => {
    const handleClick = tab => {
        props.onClick(tab);
    }
    return (
        <ul className="tabs">
            {tabs.map(tab =>
                <li
                    key={tab}
                    className={tab === props.selectedTab ? 'active' : null}
                    onClick={() => handleClick(tab)}
                >
                    {tab}
                </li>
            )}
        </ul>
    )
}

export default Tab

// practice-vue-total/src/components/Tab.vue
<template>
  <ul id="tabs" class="tabs">
    <li v-for="tab in tabs" v-bind:class="{active: tab===selectedTab}" v-on:click="onClick(tab)">{{tab}}</li>    
  </ul>
</template>

<script>
export default {
  props: ['tabs', 'selectedTab'],
  methods: {
    onClick(tab) {
      this.$emit('@click', tab);
    }
  }
}
</script>
