// practice-vue-total/src/components/SearchResult.vue
<template>
  <div v-if="searchResult.length">
    <ul>
      <li v-for="item in searchResult">
        <img v-bind:src="item.image" v-bind:alt="item.image">
        <p>{{item.name}}</p>
      </li>
    </ul>
  </div>
  <div v-else>
    {{query}} 검색어로 찾을 수 없습니다
  </div>
</template>

<script>
export default {
  props: ['searchResult', 'query'],
}
</script>

// practice-react-redux-thunk/src/components/SearchResult.jsx
import React from 'react';

const SearchResult = props => {
  const { result } = props;
  
  return (
    <div>
      {
        result.length > 0 ?
        <ul>
          {
            result.map((item, index) => {
              return (
                <li key={item.id}>
                  <img src={item.image} alt={item.image} />
                  {item.name}
                </li>
              )
            })
          }
        </ul>
        :
        <p>검색 결과가 없습니다</p>
      }
    </div>
  );
}

export default SearchResult;
