// practice-vue-last/src/components/SearchResult.vue
<template>
  <ul v-if="searchResult.length" class="list">
    <li v-for="item in searchResult">
      <img v-bind:src="item.image" v-bind:alt="item.image">
      <p>{{item.name}}</p>
    </li>
  </ul>
  <p v-else>검색 결과가 없습니다</p>
</template>

<script>
export default {
  props: ['searchResult'],
  data () {
    return {

    }
  },  
  methods: {
    
  }
}
</script>

// practice-react-redux-thunk/src/components/SearchResult.jsx
import React from 'react';

const SearchResult = props => {
  const { result } = props;
  
  return (
    <div>
      {
        result.length > 0 ?
        <ul>
          {
            result.map((item, index) => {
              return (
                <li key={item.id}>
                  <img src={item.image} alt={item.image} />
                  {item.name}
                </li>
              )
            })
          }
        </ul>
        :
        <p>검색 결과가 없습니다</p>
      }
    </div>
  );
}

export default SearchResult;
